### PR TITLE
Gseal 63 category updates

### PR DESCRIPTION
**Pull request by gpseal**
Updated Nav bar to incorporate categories from route category.list

I have updated the database to also hold colours associated with each category.

Since there are too many categories to fit in the menu, I have  split the categories into 2 parts.  First set of categories are added manually with an array called customTopics in App.tx and appears in the main section of the navigation bar.  The remaining categories will appear in a drop down menu beneath the nav bar.

image
image

The idea would be that eventually the user can choose what categories appear in the main nav bar section as their  'favorite' categories, so that they can access them without the need to open the drop down menu.

Mobile navigation has been adjusted to fit all categories.

All categories will be displayed in the footer menu as usual.

### CODE REVIEW

**Comment by AardhynLavender** [comment]
Have you thought of trying something like this. Everything on the one line.

image

Also, do we still need hard coded categories on the front-end?

**Comment by AardhynLavender** [comment]
Also, do we still need hard coded categories on the front-end?

**Comment by gpseal** [comment]
> Have you thought of trying something like this. Everything on the one line.
> 
> image
> 
> I quite like their mobile drop-down menu too.
> 
> image
> 
> @gpseal

No problem, have adjusted the nav to display all categories in a single line and removed the drop down:
image

Mobile has been adjusted slightly, but displays all categories in a single drop down
image

**Comment by gpseal** [comment]
> Also, do we still need hard coded categories on the front-end?

Have removed the array from the front end, categories now come from the database

**Review by AardhynLavender — APPROVED** [review]
Looks good. 

I like the centered logo, and the date in the corner is a nice touch.

**Review by ArtemKech — APPROVED** [review]
I like how you made these categories look neat. I also like the idea of keeping them in one line too. It's always good to fill up an empty space. Well done!

**Pull request merged**
